DECLARE --@DB_NAME VARCHAR(10),
@SQLSCRIPT VARCHAR(1000),
@TABLE_NAME VARCHAR(10),
@EMAIL_TYPE_TABLE_NAME VARCHAR(10),
@EMAIL_TABLE_NAME VARCHAR(10),
@USER_TABLE_NAME VARCHAR(10),
@ROLE_TABLE_NAME VARCHAR(10),
@IS_DROP BOOLEAN;

SET @IS_DROP = false;
--SET @DB_NAME = 'myDB';

-- Email Type
SET @TABLE_NAME = 'EMAIL_TYPE'
SET @EMAIL_TYPE_TABLE_NAME = @TABLE_NAME
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_PK'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'DROP TABLE ' + @TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						TYPE VARCHAR(255) NOT NULL,
						DESCRIPTION VARCHAR(255) NOT NULL,
						CREATEDBY DATETIME NOT NULL
					)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_PK PRIMARY KEY (ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

-- User Email
SET @TABLE_NAME = 'EMAIL'
SET @EMAIL_TABLE_NAME = @TABLE_NAME
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_PK'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_FK_' + @EMAIL_TYPE_TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'DROP TABLE ' + @TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						EMAIL_TYPE_ID INT NOT NULL,
						EMAIL_ADDRESS VARCHAR(255) NOT NULL,
						CREATEDBY DATETIME NOT NULL,
					)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_PK PRIMARY KEY (ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_FK_' + @EMAIL_TYPE_TABLE_NAME + ' FOREIGN KEY (EMAIL_TYPE_ID) REFERENCES ' + @EMAIL_TYPE_TABLE_NAME + '(ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

-- User Role
SET @TABLE_NAME = 'ROLE'
SET @ROLE_TABLE_NAME = @TABLE_NAME
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_PK'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'DROP TABLE ' + @TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						NAME VARCHAR(255) NOT NULL,
						ACTIVE BIT NOT NULL,
						CREATEDBY DATETIME NOT NULL,
					)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_PK PRIMARY KEY (ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;


-- User Profile
SET @TABLE_NAME = 'USER';
SET @USER_TABLE_NAME = @TABLE_NAME;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_PK'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'DROP TABLE ' + @TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						FIRSTNAME VARCHAR(255) NOT NULL,
						LASTNAME VARCHAR(255) NOT NULL,
						PASSWORD VARCHAR(255) NOT NULL,
						ACTIVE BIT NOT NULL,
						CREATEDBY DATETIME NOT NULL
					)';
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_PK PRIMARY KEY (ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

-- User Email Relationship
SET @TABLE_NAME = 'USER_EMAIL';
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_PK'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_FK_' + @USER_TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_FK_' + @EMAIL_TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'DROP TABLE ' + @TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						USER_ID INT NOT NULL,
						EMAIL_ID INT NOT NULL,
						ACTIVE BIT NOT NULL,
						CREATEDBY DATETIME NOT NULL
					)';
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_PK PRIMARY KEY (ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_FK_' + @USER_TABLE_NAME + ' FOREIGN KEY (USER_ID) REFERENCES ' + @USER_TABLE_NAME + '(ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_FK_' + @EMAIL_TABLE_NAME + ' FOREIGN KEY (EMAIL_ID) REFERENCES ' + @EMAIL_TABLE_NAME + '(ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

-- User Role Relationship
SET @TABLE_NAME = 'USER_EMAIL';
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
	AND @IS_DROP
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_PK'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_FK_' + @USER_TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' DROP CONSTRAINT ' + @TABLE_NAME + '_FK_' + @ROLE_TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'DROP TABLE ' + @TABLE_NAME
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'CREATE TABLE ' + @TABLE_NAME + ' (
						ID INT NOT NULL AUTO_INCREMENT,
						USER_ID INT NOT NULL,
						ROLE_ID INT NOT NULL,
						ACTIVE BIT NOT NULL,
						CREATEDBY DATETIME NOT NULL
					)';
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES IT WHERE IT.TABLE_SCHEMA = @DB_NAME AND IT.TABLE_NAME = @TABLE_NAME)
BEGIN
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_PK PRIMARY KEY (ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_FK_' + @USER_TABLE_NAME + ' FOREIGN KEY (USER_ID) REFERENCES ' + @USER_TABLE_NAME + '(ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
	SET @SQLSCRIPT = 'ALTER TABLE ' + @TABLE_NAME + ' ADD CONSTRAINT ' + @TABLE_NAME + '_FK_' + @ROLE_TABLE_NAME + ' FOREIGN KEY (ROLE_ID) REFERENCES ' + @ROLE_TABLE_NAME + '(ID)'
	CALL RUNSQLSCRIPT(@SQLSCRIPT);
END;